name: flutter_uni1_sounshield_PoC
description: Demonstrates how to integrate flutter_blue and flutter_sound to use it as walkie talkie
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_blue: "^0.5.0"
  flutter_sound: "^1.3.7"

flutter:
  uses-material-design: true